name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*' # In GitHub we still use versions type 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      repo_lower: ${{ steps.prep.outputs.repo_lower }}
      clean_tag: ${{ steps.prep.outputs.clean_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Process that remove letter 'v' and lowercase repository name for Docker Hub
      - name: Prepare names
        id: prep
        shell: bash
        run: |
          CLEAN_TAG=${GITHUB_REF_NAME#v}
          echo "clean_tag=$CLEAN_TAG" >> $GITHUB_OUTPUT

          REPO_LOWER=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Use variable that stores repository name and clean tag
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.prep.outputs.repo_lower }}:${{ steps.prep.outputs.clean_tag }}
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.prep.outputs.repo_lower }}:latest

  deploy-to-render:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy or Update Service
        run: |
          set -e

          REPO_NAME="${{ needs.build-and-push.outputs.repo_lower }}"          
          echo "Searching for service: $REPO_NAME"

          RESPONSE=$(curl -s "https://api.render.com/v1/services?name=$REPO_NAME" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}")
          
          echo "Full API Response: $RESPONSE"
          SERVICE_ID=$(echo $RESPONSE | jq -r '.[0].service.id // empty')

          if [ -n "$SERVICE_ID" ] && [ "$SERVICE_ID" != "null" ]; then
            echo "Service found with ID: $SERVICE_ID. Triggering deploy..."
            curl --fail -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
          else
            echo "--------------------------------------------------------"
            echo "ERROR: Could not find service with name: $REPO_NAME"
            echo "Please ensure the service name on Render is EXACTLY $REPO_NAME"
            echo "If service is not created, please create it manually on Render Dashboard first."
            echo "--------------------------------------------------------"
            exit 1
          fi
